from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..models import CaseRecord, ReleaseTokenRecord, utc_now

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    _PDF_OK = True
except ImportError:
    _PDF_OK = False

OUTPUT_DIR = Path("generated_documents")


@dataclass
class ConnectorResult:
    success: bool
    artifact_uri: str | None
    error: str | None
    executed_at: str


def generate_offer_letter(
    case: CaseRecord,
    token: ReleaseTokenRecord,
    facts: dict[str, Any],
) -> ConnectorResult:
    OUTPUT_DIR.mkdir(exist_ok=True)
    now_str = utc_now().isoformat()

    if _PDF_OK:
        return _pdf(case, token, facts, now_str)
    return _txt(case, token, facts, now_str)


def _pdf(
    case: CaseRecord,
    token: ReleaseTokenRecord,
    facts: dict[str, Any],
    now_str: str,
) -> ConnectorResult:
    filepath = OUTPUT_DIR / f"{case.case_id}_offer_letter.pdf"
    try:
        doc = SimpleDocTemplate(str(filepath), pagesize=letter)
        styles = getSampleStyleSheet()
        s = styles
        story = []

        story += [
            Paragraph("CANONSYS — GOVERNED OFFER AUTHORIZATION", s["Title"]),
            Spacer(1, 0.15 * inch),
            Paragraph(f"<b>Case ID:</b> {case.case_id}", s["Normal"]),
            Paragraph(f"<b>Case Type:</b> {case.case_type}", s["Normal"]),
            Paragraph(f"<b>Jurisdiction:</b> {case.jurisdiction}", s["Normal"]),
            Paragraph(f"<b>Risk Level:</b> {case.risk_level.value}", s["Normal"]),
            Paragraph(f"<b>Generated:</b> {now_str}", s["Normal"]),
            Spacer(1, 0.2 * inch),
        ]

        story += [
            Paragraph("RELEASE TOKEN", s["Heading2"]),
            Paragraph(f"<b>Token ID:</b> {token.token_id}", s["Normal"]),
            Paragraph(f"<b>Expires:</b> {token.expires_at.isoformat()}", s["Normal"]),
            Paragraph(
                f"<b>SHA-256 Signature:</b> {token.signature_metadata.get('sha256', 'N/A')}",
                s["Code"],
            ),
            Spacer(1, 0.2 * inch),
        ]

        story += [
            Paragraph("AUTHORIZED ACTION", s["Heading2"]),
            Paragraph(token.scope.get("requested_action", "N/A"), s["Normal"]),
            Spacer(1, 0.2 * inch),
        ]

        if facts:
            story.append(Paragraph("CASE FACTS", s["Heading2"]))
            fact_rows = [["Key", "Value"]] + [[k, str(v)] for k, v in facts.items()]
            tbl = Table(fact_rows, colWidths=[2.5 * inch, 4 * inch])
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ]))
            story += [tbl, Spacer(1, 0.2 * inch)]

        approver_roles = token.scope.get("approver_roles", [])
        if approver_roles:
            story.append(Paragraph("VERIFIED APPROVER CHAIN", s["Heading2"]))
            for role in approver_roles:
                story.append(Paragraph(f"✓ {role}", s["Normal"]))
            story.append(Spacer(1, 0.2 * inch))

        story += [
            Paragraph("GOVERNANCE CERTIFICATION", s["Heading2"]),
            Paragraph(
                "This document was generated by CanonSys governance infrastructure. "
                "All decisions were made by explicitly authorized human actors. "
                "The AI advisory layer held zero execution authority. "
                "This release was only issued after all policy conditions were satisfied, "
                "all required approvals were received, and the release token was validated.",
                s["Normal"],
            ),
        ]

        doc.build(story)
        return ConnectorResult(success=True, artifact_uri=str(filepath), error=None, executed_at=now_str)
    except Exception as exc:
        return ConnectorResult(success=False, artifact_uri=None, error=str(exc), executed_at=now_str)


def _txt(
    case: CaseRecord,
    token: ReleaseTokenRecord,
    facts: dict[str, Any],
    now_str: str,
) -> ConnectorResult:
    filepath = OUTPUT_DIR / f"{case.case_id}_offer_letter.txt"
    try:
        lines = [
            "CANONSYS — GOVERNED OFFER AUTHORIZATION",
            "=" * 60,
            f"Case ID   : {case.case_id}",
            f"Case Type : {case.case_type}",
            f"Jurisdiction: {case.jurisdiction}",
            f"Risk Level: {case.risk_level.value}",
            f"Generated : {now_str}",
            "",
            "RELEASE TOKEN",
            f"  Token ID : {token.token_id}",
            f"  Expires  : {token.expires_at.isoformat()}",
            f"  SHA-256  : {token.signature_metadata.get('sha256', 'N/A')}",
            "",
            "AUTHORIZED ACTION",
            f"  {token.scope.get('requested_action', 'N/A')}",
            "",
            "CASE FACTS",
        ] + [f"  {k}: {v}" for k, v in facts.items()] + [
            "",
            "VERIFIED APPROVER CHAIN",
        ] + [f"  ✓ {role}" for role in token.scope.get("approver_roles", [])] + [
            "",
            "GOVERNANCE CERTIFICATION",
            "This document was generated by CanonSys governance infrastructure.",
            "All decisions were made by explicitly authorized human actors.",
            "AI advisory layer held zero execution authority.",
            "Release issued only after all policy and approval conditions were satisfied.",
        ]
        filepath.write_text("\n".join(lines), encoding="utf-8")
        return ConnectorResult(success=True, artifact_uri=str(filepath), error=None, executed_at=now_str)
    except Exception as exc:
        return ConnectorResult(success=False, artifact_uri=None, error=str(exc), executed_at=now_str)
